fix onBoarding sliding
Horizontal-org/Tella-Android pull request #183
Opened 2023-01-24 17:23 UTC by wafalakhal

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardCameraFragment.kt
> +
Extra line space :)

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardFilesFragment.kt
> +      //  (activity as OnBoardActivityInterface).setCurrentIndicator(2)
maybe remove the old code?

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +        viewPager = findViewById(R.id.view_pager)
We are using `viewBinding` in the project.

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +
You can format the code using òption+command`enter :)

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +            viewPager.currentItem = viewPager.currentItem - 1
make sure `viewPager.size > 0`

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +        }
what does ìtems` stands for?

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +        /* showDualChoiceTypeSheet(this.supportFragmentManager,
Same here let's remove the old code

2023-01-25 12:30 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +                    1 -> OnBoardCameraFragment()
Let's use an enum instead :)

2023-01-26 11:59 UTC, djordjemarusic approved these changes

2023-01-26 12:22 UTC, ahlem-jarrar requested changes

2023-01-26 12:22 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +    val ONBOARDING_INTRODUCTION_VIEW_INDEX = 0
This should be constants not an attributes in the class.

2023-01-26 12:22 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +        backBtn = findViewById(R.id.back_btn)
where is the viewBinding here :)

2023-01-26 13:44 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +        backBtn = findViewById(R.id.back_btn)
@wafalakhal also resolve this comments if it's fixed.

2023-01-26 18:44 UTC, ahlem-jarrar requested changes

2023-01-26 18:44 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardCameraFragment.kt
>      private lateinit var backBtn: TextView
why initializing this ? while already using viewBinding ?

2023-01-26 18:44 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardCameraFragment.kt
>      private lateinit var backBtn: TextView
@wafalakhal please don't forget to resolve the comments.

2023-01-26 18:44 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/onboarding/OnBoardingActivity.kt
> +    val ONBOARDING_LOCK_VIEW_INDEX = 4
this should be private as you only need it in this class.

2023-01-27 08:49 UTC, ahlem-jarrar approved these changes

2023-01-30 14:32 UTC, merged