add new icons to camouflage setting
Horizontal-org/Tella-Android pull request #191
Opened 2023-03-08 09:48 UTC by wafalakhal

add new icons to camouflage setting

2023-03-08 10:46 UTC, djordjemarusic approved these changes

2023-03-08 17:17 UTC, ahlem-jarrar requested changes

2023-03-08 17:17 UTC, ahlem-jarrar commented on mobile/src/main/res/values/strings.xml
>      <string name="fragment_mic">Microphone</string>
We should put the strings in other files translation.

2023-03-08 17:17 UTC, ahlem-jarrar commented on mobile/src/main/res/values/ic_watch_background.xml
> +</resources>
This is a duplicated resources that we must remove.

2023-03-08 17:17 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/util/CamouflageManager.java
> +        options.add(new CamouflageOption(getOptionAlias("Workout"), R.mipmap.ic_workout_round, R.string.settings_camo_workout));
Can we add a constant file that contains all this hard coded strings.

2023-03-09 11:59 UTC, ahlem-jarrar approved these changes

2023-03-09 17:37 UTC, merged