Auto report implementation
Horizontal-org/Tella-Android pull request #209
Opened 2023-04-18 12:31 UTC by ahlem-jarrar

2023-04-18 12:46 UTC, djordjemarusic commented on mobile/src/main/res/values/strings.xml
Everything here should be translatable.

2023-05-28 20:47 UTC, djordjemarusic requested changes

2023-05-31 15:17 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/util/StatusProviderImpl.kt
> +            return networkCapabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) ||
we could use the run function here to simplify the code, maybe like this 
           val network = cm.activeNetwork
            val networkCapabilities = cm.getNetworkCapabilities(network)
            return networkCapabilities?.run {
                hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR) ||
                        hasTransport(NetworkCapabilities.TRANSPORT_WIFI) ||
                        hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)
            } ?: false

2023-05-31 15:17 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/util/StatusProviderImpl.kt
> +            val ni = cm.activeNetworkInfo
maybe we could use more expressive naming here instead of "ni"

2023-05-31 16:10 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/TellaFileUploadSchedulePresenter.java
> +                    view.onMediaFilesUploadScheduled();
I don't think we can do this here as this part is still `MVP` and will need to be refactored later I guess!

2023-05-31 19:32 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/mvp/presenter/TellaFileUploadSchedulePresenter.java
> +                                    .setRequiredNetworkType(NetworkType.CONNECTED)
Let's propose this to the team then :).

2023-06-05 09:25 UTC, wafalakhal approved these changes

2023-06-05 09:33 UTC, merged