EXIF deletion when importing files
Horizontal-org/Tella-Android pull request #211
Opened 2023-05-09 08:22 UTC by djordjemarusic

T-And-1167 - Implement EXIF deletion when importing files

2023-05-15 22:50 UTC, ahlem-jarrar requested changes

2023-05-15 22:50 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
> +        while ((length = source.read(buf)) != -1) {
can we rename `length` to `bytesRead` to make it more descriptive?

2023-05-15 22:50 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/settings/SecuritySettings.kt
> +
what do you think about using apply scope function here ?
```
keepExifTellaSwitch.mSwitch.apply {
    isChecked = Preferences.isKeepExif()
    setOnCheckedChangeListener { _, isChecked ->
        Preferences.setKeepExif(isChecked)
    }
}
```

2023-05-15 22:50 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
> +        Boolean keepExif = Preferences.isKeepExif();
Let's  change `Boolean` to `boolean` for the keepExif variable, as it is a primitive type.

2023-05-15 22:50 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
>          ByteArrayOutputStream v_thumb_jpeg_stream = new ByteArrayOutputStream();
what do you think about renaming `v_image_jpeg_stream` to `imageJpegStream` and `v_thumb_jpeg_stream` to `thumbJpegStream` to follow Java naming conventions and improve readability?

2023-05-15 22:50 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
>          v_thumb.compress(Bitmap.CompressFormat.JPEG, 100, v_thumb_jpeg_stream);
- Let's use the try-with-resources statement to automatically close the input streams (inputStream and input) after use, reducing the need for explicit close calls.
- Combine the declaration and assignment of the inputStream variable within the try block for better scoping and resource handling.
- Reordered the code to improve readability and logical flow.
- Utilized try-with-resources for the input stream within the keepExif branch to automatically close the stream after use.

 ```
    boolean keepExif = Preferences.isKeepExif();
    ByteArrayOutputStream imageJpegStream = new ByteArrayOutputStream();
    ByteArrayOutputStream thumbJpegStream = new ByteArrayOutputStream();
 try (InputStream inputStream = context.getContentResolver().openInputStream(uri)) {
        Bitmap originalBitmap = modifyOrientation(BitmapFactory.decodeStream(inputStream), inputStream); // bitmap of photo
        Bitmap thumbnail = ThumbnailUtils.extractThumbnail(originalBitmap, originalBitmap.getWidth() / 10, originalBitmap.getHeight() / 10); // bitmap of thumb
        thumbnail.compress(Bitmap.CompressFormat.JPEG, 100, thumbJpegStream);

        if (keepExif) {
            try (InputStream input = context.getContentResolver().openInputStream(uri)) {
                copyStream(input, imageJpegStream);
            }
        } else {
            if (!originalBitmap.compress(Bitmap.CompressFormat.JPEG, 100, imageJpegStream)) {
                throw new Exception("JPEG compression failed");
            }
        }
    }
```

2023-05-16 09:23 UTC, wafalakhal approved these changes

2023-05-16 10:29 UTC, merged