Forms refactor
Horizontal-org/Tella-Android pull request #223
Opened 2023-07-13 08:42 UTC by djordjemarusic

2023-07-26 18:15 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/FormSubmitActivity.kt
> +                /*DialogsUtil.showExitWithSubmitDialog(this,
let's get rid of commented code

2023-07-26 18:15 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/FormSubmitActivity.kt
> +        with(submitModel) {
maybe it is better to use a function just to initObservers to maintain a clear code

2023-07-26 18:15 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/CollectFormEntryActivity.kt
> +        disposables.wire(
maybe we could call some method here instead of putting code in the onCreate and also remove commented code

2023-07-27 16:09 UTC, ahlem-jarrar requested changes

2023-07-27 16:09 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SubmittedFormsListFragment.kt
>      FragmentSubmittedFormsListBinding::inflate
We should inject the `ViewModel` here too

2023-07-27 16:09 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SubmittedFormsListFragment.kt
> +    private val model: SharedFormsViewModel by viewModels()
Can we rename it to `viewModel`?

2023-07-27 16:09 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SubmittedFormsListFragment.kt
> +                success!!
Why this `Boolean` is nullable?

2023-07-27 16:09 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/forms/SubmittedFormsListFragment.kt
> +            form?.let {
this form doesn't seem to be a `Nullable`?

2023-07-28 06:22 UTC, ahlem-jarrar approved these changes

2023-07-28 07:21 UTC, merged