refactor VideoViewer, AudioViewer and PhotoViewer activities
Horizontal-org/Tella-Android pull request #224
Opened 2023-07-17 17:47 UTC by wafalakhal

Add sharedViewmodel to encapsulate common functions 
Add a common VaultActionHelper 
refactor old code  of the three activities
change the permissions requests using contracts instead of activityResults method

2023-07-19 07:19 UTC, djordjemarusic commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/AudioPlayActivity.kt
> +    var mPlay: ImageButton? = null
Can we make elements like this not null?

2023-07-19 07:20 UTC, djordjemarusic commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/AudioPlayActivity.kt
> +        mPlay = binding!!.content.playAudio
Assertions like this are unnecessary

2023-07-19 07:44 UTC, djordjemarusic commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/AudioPlayActivity.kt
> +        mPlay!!.setImageDrawable(this.resources.getDrawable(R.drawable.ic_play_arrow_white_24dp))
this getDrawable call is depricated

2023-07-19 07:47 UTC, djordjemarusic commented
In general, we are also cleaning the code so warnings should be handled in the classes we are working on.

2023-07-26 17:37 UTC, djordjemarusic approved these changes

2023-07-28 06:49 UTC, ahlem-jarrar requested changes

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/PhotoViewerActivity.kt
> +class PhotoViewerActivity : BaseLockActivity(), StyledPlayerView.ControllerVisibilityListener {
We should use hilt to inject the `ViewModel` and other dependencies.

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/PhotoViewerActivity.kt
> +            binding.toolbar.outlineProvider = null
There should be an extension function in Djordje's PR now, that you can use configure the appBar

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/SharedMediaFileViewModel.kt
> +        disposables.add(MyApplication.rxVault.delete(vaultFile)
Why `VaultFile`is nullable? if needed we should have an early return no?

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/SharedMediaFileViewModel.kt
> +        disposables.add(
Same here why the is nullable, let's have an early return, and apply the logic on the rest of the code please.

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/VaultActionsHelper.kt
> +                context, Manifest.permission.READ_EXTERNAL_STORAGE
Do you think we should have a separate helper to hold the permissions?

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/VideoViewerActivity.kt
> +class VideoViewerActivity : BaseLockActivity(), StyledPlayerView.ControllerVisibilityListener {
Same here let's use dagger if needed!

2023-07-28 06:49 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/viewer/VideoViewerActivity.kt
> +        simpleExoPlayerView = findViewById(R.id.player_view)
why we don't access this with `binding`here?

2023-08-02 09:51 UTC, merged