Fixes for v2.4
Horizontal-org/Tella-Android pull request #235
Opened 2023-09-07 19:12 UTC by djordjemarusic

Pull requests should be opened against the `develop` branch. For more information on contributing to Tella source code, see the [Contributor Guidelines](contributing/contributor_guide.md).

## Type of change

**Description:**

**Select the type of change(s) made in this pull request:**
- [ ] Bug fix *(Fixes an issue)*
- [ ] New feature *(Adds functionality)*
- [ ] Documentation *(Fix to documentation)*

----------------------------------------------------------------------------------------

Fixes #issue-number

## Proposed changes 

*
*
*

2023-09-08 09:40 UTC, ahlem-jarrar requested changes

2023-09-08 09:40 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/reports/ReportsFragment.kt
> +    private var initializedView: Boolean = false
Let's rename it to `isViewInitialized`, do you think we should define this in a `BaseFragment` ?

2023-09-08 09:56 UTC, djordjemarusic commented on tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/calculator/Evaluator.java
> +
This raises more issues. PercentageValue should be "a nice" string to be included in calculation, and transfering the whole class to Kotlin can be time consuming at this point. Also, I don't think we should try to fix the input by removing the non digits, there may be other operators. And if the input is not valid, we should just print error like normal calculator.

2023-09-08 10:03 UTC, ahlem-jarrar commented on tella-locking-ui/src/main/java/com/hzontal/tella_locking_ui/ui/pin/calculator/Evaluator.java
> +
Why transforming the class into kotlin is time consuming I think you should all the time you need to implement this in Kotlin :).

2023-09-10 08:02 UTC, ahlem-jarrar approved these changes

2023-09-10 08:02 UTC, merged