Background encryption files
Horizontal-org/Tella-Android pull request #246
Opened 2023-11-09 09:55 UTC by ahlem-jarrar

2023-11-21 12:57 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/bus/event/RecentBackgroundActivitiesEvent.java
> +}
maybe we could change this code to kotlin as it is a new class

2023-11-21 21:01 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/domain/usecases/shared/ScheduleUploadReportFilesUseCase.kt
> +                // Perform the upload report operation and complete the Completable
Let's add a doFinally block to ensure that the work is cleared from WorkManager using "cancelUniqueWork" after the upload report operation is completed.

2023-11-22 15:36 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/util/TopSheetTestUtils.kt
> +                .screenTag("BackgroundActivitiesSheet").cancellable(true)
why we are setting the tag here ?

2023-11-22 15:52 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/camera/CameraActivity.kt
> +               this, getString(R.string.gallery_dialog_expl_encrypting)
let's delete that if it not needed

2023-11-22 15:53 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/camera/CameraActivity.kt
> +        //    hideProgressDialog()
and this too

2023-11-22 15:59 UTC, wafalakhal reviewed
let's add some technical documentation on new files and methods 
Maybe we could add some unit test as well

2023-11-23 11:03 UTC, djordjemarusic commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/camera/CameraViewModel.kt
> +                val backgroundVideoFile = BackgroundActivityModel(
We should rename backgroundVideoFile to something like backgroundFile since it could be photo or video and we are adding mimeType.

2024-06-03 08:50 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
> +            if (mimeType != null) {
Let's add a method "importUriByMimeType" that handles the logic for determining which import function to call based on the MIME type.

2024-06-03 08:51 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/media/MediaFileHandler.java
> +        if (uri.getScheme().equals("content")) {
let's put "content" in constant variable

2024-06-03 09:40 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/util/TopSheetTestUtils.kt
> +                    descriptionText.observe(lifecycleOwner) {
let's rename it to newDescription for more readability

2024-06-03 13:39 UTC, wafalakhal requested changes

2024-06-04 10:25 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/activity/camera/CameraFragment.kt
I think we should keep this fragment and refactor step by step as doing thing apply to change every where in the app.

2024-06-04 10:41 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/recorder/MicFragment.kt
> +        viewModel.recordingStoppedLiveData.observe(viewLifecycleOwner, ::onRecordingStopped)
@wafalakhal  The code is already readable and follows standard Kotlin practices, making additional scoping with functions like apply, run, let, or also unnecessary...

2024-06-19 11:21 UTC, merged