Accessibility options
Horizontal-org/Tella-Android pull request #247
Opened 2023-11-16 22:13 UTC by djordjemarusic

Text justification switch, text spacing switch,
For yellow button components, change the text from white to black

2023-11-17 15:05 UTC, ahlem-jarrar requested changes
let's add some unit test please :)

2023-11-17 15:05 UTC, ahlem-jarrar commented on shared-ui/src/main/java/org/hzontal/shared_ui/bottomsheet/BottomSheetUtils.kt
> +    const val SHORT_TIMEOUT: Long = 1500
if lot let's mark it private

2023-11-21 10:12 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt
> +                refreshFragment()
let's combine the code for textJustificationSwitch and textSpacingSwitch into a function to avoid redundancy.

2023-11-22 13:50 UTC, djordjemarusic commented on mobile/src/main/java/rs/readahead/washington/mobile/views/fragment/uwazi/entry/UwaziEntryFragment.kt
> +        ViewModelProvider(baseActivity)[SharedUwaziSubmissionViewModel::class. java]
It's kind of out of the scope of this PR, but sure, why not...

2023-11-24 10:52 UTC, wafalakhal commented on mobile/src/main/java/rs/readahead/washington/mobile/views/settings/GeneralSettings.kt
> +                refreshFragment()
I meant using some method like this                                                                                                                       
    private fun setupSwitch(
    switch: CompoundButton?,
    isEnabled: () -> Boolean,
    setEnabled: (Boolean) -> Unit,
    refresh: () -> Unit
) {         
for both textJustificationSwitch and textSpacingSwitch

2023-12-10 18:10 UTC, ahlem-jarrar reviewed
Maybe we can apply this last comment review and we can merge :)

2023-12-10 18:10 UTC, ahlem-jarrar commented on mobile/src/main/java/rs/readahead/washington/mobile/util/ThemeStyleManager.kt
> +            if (Preferences.isTextJustification()) {
may we can simplify the code private
 ```
fun getThemeStyleBasedOnPreferences(
    defaultStyle: Int,
    lineSpacingStyle: Int,
    justifyStyle: Int,
    lineSpacingJustifyStyle: Int
): Int {
    val isTextSpacingEnabled = Preferences.isTextSpacing()
    val isTextJustificationEnabled = Preferences.isTextJustification()

    return when {
        isTextSpacingEnabled && isTextJustificationEnabled -> lineSpacingJustifyStyle
        isTextSpacingEnabled -> lineSpacingStyle
        isTextJustificationEnabled -> justifyStyle
        else -> defaultStyle
    }
}
```

2023-12-11 11:20 UTC, merged